# Generated by Django 4.0.4 on 2022-07-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Finished')], default=0)),
            ],
        ),
    ]
